export const bookDatas = [
  {
    id: 1,
    title: "Hello",
    author: "HelloMan",
    date: "today",
    note: "what a crazy book!",
    category: "Romance",
    favorite: true,
  },
  {
    id: 2,
    title: "how are you?",
    author: "GoodMourningGirl",
    date: "today",
    note: "what a cool book!",
    category: "Science Fiction",
    favorite: false,
  },
  {
    id: 3,
    title: "I am fine",
    author: "GoodNightBoy",
    date: "today",
    note: "what a cute book!",
    category: "Romance",
    favorite: true,
  },
  {
    id: 4,
    title: "I might be wrong",
    author: "Somebody",
    date: "today",
    note: "what a nice book!",
    category: "Romance",
    favorite: false,
  },
  {
    id: 5,
    title: "MidNightPurple",
    author: "Araki",
    date: "today",
    note: "what a fantastic book!",
    category: "Romance",
    favorite: true,
  },
  {
    id: 6,
    title: "War of Science",
    author: "Tezuka",
    date: "today",
    note: "what a futuristic book!",
    category: "SienceFiction",
    favorite: true,
  },
  {
    id: 7,
    title: "Art & Design",
    author: "Pabulo Picaso",
    date: "today",
    note: "what a realstic book!",
    category: "Art",
    favorite: true,
  },
];
